name: XMLTools with SaxonC-HE 12.8.0 with manual tag

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'v12.8.0 beta'
        required: true
        default: 'latest-manual'

jobs:
  build-x64:
    runs-on: windows-2022
    outputs:
      RELEASE_TAG: ${{ steps.set-tag.outputs.RELEASE_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Checkout Custom libxml2
        uses: actions/checkout@v4
        with:
          repository: haja-fgabriel/libxml2
          ref: haja.floring/addXPathVerification
          path: libxml2_source

      - name: Build Custom libxml2 (x64)
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cd libxml2_source\win32
          cscript configure.js compiler=msvc prefix=..\build include=..\include lib=..\lib iconv=no icu=no zlib=no
          nmake /f Makefile.msvc
          nmake /f Makefile.msvc install

      - name: Patch Project
        shell: pwsh
        run: |
          $libxmlBase = "$(Get-Location)\libxml2_source\build"
          $saxonInc = "$(Get-Location)\main\SaxonCHEHelper\include\saxonc"

          # Suppress warning C4251 and add the path to Saxon
          # /wd4251 - Disables the dll-interface warning
          echo "CL=/I`"$libxmlBase\include\libxml2`" /I`"$saxonInc`" /wd4251" >> $env:GITHUB_ENV

          $libxmlBase = "$(Get-Location)\libxml2_source\build"
          $projFile = "main\XMLTools.vcxproj"
          (Get-Content $projFile) `
            -replace '[^; \t\r\n]+\\libxml2\.lib', 'libxml2.lib' `
            -replace '<PrecompiledHeader>Use</PrecompiledHeader>', '<PrecompiledHeader>NotUsing</PrecompiledHeader>' | Set-Content $projFile

          vcpkg integrate install
          vcpkg install gtest:x64-windows
          echo "CL=/I`"$libxmlBase\include\libxml2`" /I`"C:\vcpkg\installed\x64-windows\include`"" >> $env:GITHUB_ENV
          echo "LINK=/LIBPATH:`"$libxmlBase\lib`" libxml2.lib" >> $env:GITHUB_ENV
          echo "LIBXML_DLL_PATH=$libxmlBase\bin\libxml2.dll" >> $env:GITHUB_ENV

      - name: Build x64
        run: |
          cd main
          nuget restore XMLTools.sln
          msbuild XMLTools.sln /m /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143

      - name: Prepare Artifact
        id: set-tag
        shell: pwsh
        run: |
          $inputTag = "${{ github.event.inputs.release_version }}".Trim()
          $branchName = "${{ github.ref_name }}".Replace("/", "-")

          $tagName = "$inputTag-$branchName"
          $archiveName = "XMLTools_$($tagName)_x64.7z"

          echo "RELEASE_TAG=$tagName" >> $env:GITHUB_OUTPUT
          echo "ARCHIVE_NAME=$archiveName" >> $env:GITHUB_ENV

          New-Item -ItemType Directory -Path "dist" -Force
          Copy-Item "main\x64\Release\XMLTools.dll", "main\install\ReadMe.txt" -Destination "dist\"
          Copy-Item "$env:LIBXML_DLL_PATH" -Destination "dist\"

          if ("${{ github.ref_name }}" -eq "UpdateToSaxonC128") {
          Write-Host "Downloading SaxonC HE 12.8 binaries..."
          $saxonCoreUrl = "https://raw.githubusercontent.com/martin-honnen/xmltools/refs/heads/UpdateToSaxonC128/SaxonCHEHelper/bin/saxonc-core-he.dll"
          $saxonHeUrl = "https://raw.githubusercontent.com/martin-honnen/xmltools/refs/heads/UpdateToSaxonC128/SaxonCHEHelper/bin/saxonc-he.dll"
          Invoke-WebRequest -Uri $saxonCoreUrl -OutFile "dist\saxonc-core-he.dll"
          Invoke-WebRequest -Uri $saxonHeUrl -OutFile "dist\saxonc-he.dll"
          }

          7z a -t7z -mx9 "$archiveName" ./dist/*

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: xmltools-x64
          path: "*.7z"

  publish:
    needs: [build-x64]
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: xmltools-*
          merge-multiple: true

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # take the tag from the output of the build-x64 job.
          tag_name: ${{ needs.build-x64.outputs.RELEASE_TAG }}
          files: "*.7z"
          generate_release_notes: true
          # make it a pre-release if it's not an official tag
          prerelease: ${{ github.ref_type != 'tag' }}
          # for manual restarts:
          make_latest: ${{ github.ref_type == 'tag' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
