name: Build XMLTools

on:
#  push:
#    branches: [ main ]
#    tags: [ 'v*' ]
#  pull_request:
#    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        platform: [Win32, x64]
        configuration: [Release]
        toolset: [v143]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # run: |
          # git submodule update --init --recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Install Dependencies (vcpkg)
        run: |
          # vcpkg integration with MSBuild (automatically sets include/lib paths)
          vcpkg integrate install
          
          # Installing libxml2 and gtest for the required architectures
          if ("${{ matrix.platform }}" -eq "x64") {
            vcpkg install libxml2:x64-windows gtest:x64-windows
          }
          if ("${{ matrix.platform }}" -eq "Win32") {
            vcpkg install libxml2:x86-windows gtest:x86-windows
          }

#      - name: Restore NuGet Packages
#        run: |
#          nuget restore SimpleXmlLib\SimpleXmlTests\packages.config -PackagesDirectory packages
          
      - name: Restore NuGet Packages2
        run: |
          nuget restore XMLTools.sln

      - name: Build Solution
        run: |
          msbuild XMLTools.sln `
            /m `
            /p:Configuration="${{ matrix.configuration }}" `
            /p:Platform="${{ matrix.platform }}" `
            /p:PlatformToolset="${{ matrix.toolset }}"

      - name: Prepare Artifacts
        if: matrix.configuration == 'Release'
        shell: pwsh
        run: |
          $platform = "${{ matrix.platform }}"
          $archi = if ($platform -eq "Win32") { "x86" } else { "x64" }
          $tagName = if ("${{ github.ref_type }}" -eq "tag") { "${{ github.ref_name }}" } else { "latest-build" }
          $archiveName = "XMLTools_$($tagName)_$($archi).7z"

          $dllPath = "$platform\${{ matrix.configuration }}\XMLTools.dll"

          if (Test-Path $dllPath) {
              7z a -t7z -mx9 $archiveName $dllPath
              echo "ARCHIVE_NAME=$archiveName" >> $env:GITHUB_ENV
          } else {
              Write-Error "DLL not found at $dllPath"
              exit 1
          }

      - name: Upload to Workflow
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.platform }}
          path: XMLTools_*.7z
          retention-days: 1

  publish:
    needs: build
    if: github.event_name != 'pull_request' && (github.ref_type == 'tag' || github.ref_name == 'main')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          merge-multiple: true

      - name: Set Release Tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "RELEASE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "RELEASE_TAG=latest-build" >> $GITHUB_ENV
          fi

      - name: Delete Old Release (Auto-builds only)
        if: github.ref_type != 'tag'
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: "*.7z"
          generate_release_notes: true
          prerelease: ${{ github.ref_type != 'tag' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
